### ISSUE TITLE
【pyenergyplus】OSError: exception: access violation reading 0xFFFFFFFFFFFFFFFF

### ISSUE THREAD

**Issue by Katherinaxxx** [NREL/EnergyPlus#9280]
I got this error, dont how to fix it
```
Stack (most recent call first):
  File "C:\EnergyPlusV9-3-0\pyenergyplus\runtime.py", line 119 in run_energyplus
  File "C:\Users\35939\anaconda3\envs\rllib\lib\threading.py", line 870 in run
  File "C:\Users\35939\anaconda3\envs\rllib\lib\threading.py", line 932 in _bootstrap_inner
  File "C:\Users\35939\anaconda3\envs\rllib\lib\threading.py", line 890 in _bootstrap
Exception in thread Thread-5:
Traceback (most recent call last):
  File "C:\Users\35939\anaconda3\envs\rllib\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\35939\anaconda3\envs\rllib\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\EnergyPlusV9-3-0\pyenergyplus\runtime.py", line 119, in run_energyplus
    return self.api.energyplus(len(args_with_program_name), cli_args)
OSError: exception: access violation reading 0xFFFFFFFFFFFFFFFF
```

energyplus 9.3.0

**Comment by bonnema** [comment]
Can you share your .idf and .py file?

**Comment by jmarrec** [comment]
@Katherinaxxx can you share your .idf and .py file so we have a chance to reproduce the issue please?

**Comment by Katherinaxxx** [comment]
I reinstalled energyplus and python. And everything works fine now, thanks for your time :) @jmarrec
